<a href="https://colab.research.google.com/github/LukeBlanch/CAP4630-Artificial-Intelligence/blob/master/HW_4/HW_4_Problem_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Homework 4 Problem 2:
## Luke Blanchard

## Imports

In [0]:
import numpy as np

## maxpooling2d function

In [0]:
def maxpooling2d(input_mat, s):

  # Make sure the input matrix is square
  if (input_mat[:,0].size != input_mat[0].size):
    raise ValueError('Input matrix should be square, but was ', input_mat[0].size, 'X', input_mat[:,0].size)

  # Make sure the input matrix and window size are compatible
  if (s > input_mat[0].size):
    raise ValueError('Window size s incompatible with input matrix')

  size = input_mat[0].size
  outputSize = int(size / s)
  output_mat = np.zeros((outputSize, outputSize))

  for i in range(0, size, s):
    if ((i + s) > size):
      break
    for j in range(0, size, s):
      if ((j + s) > size):
        break
      max = 0
      # Find the maximum value in the current window
      for x in range(i,i+s):
        for y in range(j,j+s):
          if (input_mat[x][y] > max):
            max = input_mat[x][y]
      # Add the maximum window value to the output matrix
      output_mat[int(i/s)][int(j/s)] = max

  return output_mat

### Example with a 5x5 input and a 2x2 window

In [0]:
input_mat = np.array([[1,2,1,2,2],[3,1,2,2,1],[1,3,2,1,3],[2,2,1,3,2],[3,2,1,1,3]])

output_mat = maxpooling2d(input_mat, 2)
print(output_mat)

[[3. 2.]
 [3. 3.]]


### Example with a 5x5 input and a 1x1 window, note the output matrix is the same as the input

In [0]:
input_mat = np.array([[1,2,1,2,2],[3,1,2,2,1],[1,3,2,1,3],[2,2,1,3,2],[3,2,1,1,3]])

output_mat = maxpooling2d(input_mat, 1)
print(output_mat)

[[1. 2. 1. 2. 2.]
 [3. 1. 2. 2. 1.]
 [1. 3. 2. 1. 3.]
 [2. 2. 1. 3. 2.]
 [3. 2. 1. 1. 3.]]


### Example with a 5x5 input and a 5x5 window

In [0]:
input_mat = np.array([[1,2,1,2,2],[3,1,2,2,1],[1,3,2,1,3],[2,2,1,3,2],[3,2,1,1,3]])

output_mat = maxpooling2d(input_mat, 5)
print(output_mat)

[[3.]]


### Example with a 6x6 input and a 3x3 window

In [0]:
input_mat = np.array([[1,2,1,2,2,2],[3,1,2,2,1,0],[1,3,2,1,3,1],[2,2,1,3,2,1],[3,2,1,1,3,1],[1,2,2,1,1,0]])

output_mat = maxpooling2d(input_mat, 3)
print(output_mat)

[[3. 3.]
 [3. 3.]]


In [0]:
import skimage.measure

input_mat = []
expected_mat = []
s = []
input_mat.append(np.array([[1, 2, 1, 2],
                      [2, 4, 2, 1],
                      [1, 2, 4, 2],
                      [2, 1, 2, 1]]))
s.append(2)

expected_mat.append(np.array([[4, 2],
                                [2, 4]]))

input_mat.append(np.array([[1, 2, 1, 2, 4, 5],
                      [2, 4, 2, 1, 0, 3],
                      [1, 2, 4, 2, 4, 5],
                      [2, 1, 2, 1, 2, 1],
                      [1, 1, 2, 3, 1, 2]]))
s.append(2)

expected_mat.append([[4, 2, 5],
 [2, 4, 5],
 [1, 3, 2]])


for i in range(len(input_mat)):
  # uncomment top line and comment second line to test code
  output_mat = maxpooling2d(input_mat[i], s[i])
  #output_mat = skimage.measure.block_reduce(input_mat[i], (s[i],s[i]), np.max)

  print(output_mat)

  if np.array_equal(output_mat, expected_mat[i]):
    print("Correct output!")
  else:
    print("Incorrect output!")

[[4. 2.]
 [2. 4.]]
Correct output!


ValueError: ignored