<a href="https://colab.research.google.com/github/LukeBlanch/CAP4630-Artificial-Intelligence/blob/master/HW_4/HW_4_Problem_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Homework 4 Problem 1:
## Luke Blanchard

## Imports

In [0]:
import numpy as np

## conv2d function

In [0]:
def conv2d(input_mat, kernel_mat):
  # Make sure the input matrix is square
  if (input_mat[:,0].size != input_mat[0].size):
    raise ValueError('Input matrix should be square, but was ', input_mat[0].size, 'X', input_mat[:,0].size)

  # Make sure the kernel matrix is square
  if (kernel_mat[:,0].size != kernel_mat[0].size):
    raise ValueError('Kernel matrix should be square, but was ', kernel_mat[0].size, 'X', kernel_mat[:,0].size)

  # Make sure the kernel matrix is odd
  #if ((kernel_mat[0].size % 2) != 1):
   # raise ValueError('Kernel matrix size must be odd')

  # Make sure the input and kernel matrix are compatible
  if (kernel_mat[0].size > input_mat[0].size):
    raise ValueError('Kernel matrix incompatible with input matrix')

  outputSize = input_mat[0].size - kernel_mat[0].size + 1
  output_mat = np.zeros((outputSize, outputSize))

  for i in range(output_mat[0].size):
    for j in range(output_mat[0].size):
      for x in range(i, i + kernel_mat[0].size):
        for y in range (j, j + kernel_mat[0].size):
          output_mat[i][j] += (input_mat[x][y] * kernel_mat[x-i][y-j])



  return output_mat

### Example with a 5x5 input and a 3x3 kernel

In [0]:
input_mat = np.array([[1,2,1,2,2],[3,1,2,2,1],[1,3,2,1,3],[2,2,1,3,2],[3,2,1,1,3]])
kernel_mat = np.array([[1,2,1],[2,1,2],[1,2,1]])

output_mat = conv2d(input_mat, kernel_mat)
print(output_mat)

[[26. 22. 22.]
 [23. 24. 27.]
 [25. 24. 22.]]


### Example with a 5x5 input and a 1x1 kernel, note the output matrix is the same as the input

In [0]:
input_mat = np.array([[1,2,1,2,2],[3,1,2,2,1],[1,3,2,1,3],[2,2,1,3,2],[3,2,1,1,3]])
kernel_mat = np.array([[1]])

output_mat = conv2d(input_mat, kernel_mat)
print(output_mat)

[[1. 2. 1. 2. 2.]
 [3. 1. 2. 2. 1.]
 [1. 3. 2. 1. 3.]
 [2. 2. 1. 3. 2.]
 [3. 2. 1. 1. 3.]]


### Example with a 5x5 input and a 5x5 kernel

In [0]:
input_mat = np.array([[1,2,1,2,2],[3,1,2,2,1],[1,3,2,1,3],[2,2,1,3,2],[3,2,1,1,3]])
kernel_mat = np.array([[1,2,1,2,2],[3,1,2,2,1],[1,3,2,1,3],[2,2,1,3,2],[3,2,1,1,3]])

output_mat = conv2d(input_mat, kernel_mat)
print(output_mat)

[[103.]]


### Example with a 4x4 input and a 3x3 kernel

In [0]:
input_mat = np.array([[1,2,1,2],[3,1,2,2],[1,3,2,1],[2,2,1,3]])
kernel_mat = np.array([[1,2,1],[2,1,2],[1,2,1]])

output_mat = conv2d(input_mat, kernel_mat)
print(output_mat)

[[26. 22.]
 [23. 24.]]


In [0]:
input_mat = np.array([[1,2,1,2],[3,1,2,2],[1,3,2,1],[2,2,1,3]])
kernel_mat = np.array([[1,2],[2,1]])

output_mat = conv2d(input_mat, kernel_mat)
print(output_mat)

[[12.  8. 11.]
 [10. 13. 11.]
 [13. 12.  9.]]
